/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSearchRouteImport } from './routes/shop/search'
import { Route as ShopProductRouteImport } from './routes/shop/product'
import { Route as ShopPopupRouteImport } from './routes/shop/popup'
import { Route as ShopOrdersRouteImport } from './routes/shop/orders'
import { Route as ShopNightmareRouteImport } from './routes/shop/nightmare'
import { Route as ShopCheckoutRouteImport } from './routes/shop/checkout'
import { Route as ShopCategoryRouteImport } from './routes/shop/category'
import { Route as ShopCartRouteImport } from './routes/shop/cart'
import { Route as ShopAccountRouteImport } from './routes/shop/account'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/shop/search',
  path: '/shop/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductRoute = ShopProductRouteImport.update({
  id: '/shop/product',
  path: '/shop/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopPopupRoute = ShopPopupRouteImport.update({
  id: '/shop/popup',
  path: '/shop/popup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/shop/orders',
  path: '/shop/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopNightmareRoute = ShopNightmareRouteImport.update({
  id: '/shop/nightmare',
  path: '/shop/nightmare',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/shop/checkout',
  path: '/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/category',
  path: '/shop/category',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/shop/cart',
  path: '/shop/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/shop/account',
  path: '/shop/account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/category': typeof ShopCategoryRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/nightmare': typeof ShopNightmareRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/popup': typeof ShopPopupRoute
  '/shop/product': typeof ShopProductRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/category': typeof ShopCategoryRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/nightmare': typeof ShopNightmareRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/popup': typeof ShopPopupRoute
  '/shop/product': typeof ShopProductRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/category': typeof ShopCategoryRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/nightmare': typeof ShopNightmareRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/popup': typeof ShopPopupRoute
  '/shop/product': typeof ShopProductRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/category'
    | '/shop/checkout'
    | '/shop/nightmare'
    | '/shop/orders'
    | '/shop/popup'
    | '/shop/product'
    | '/shop/search'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/category'
    | '/shop/checkout'
    | '/shop/nightmare'
    | '/shop/orders'
    | '/shop/popup'
    | '/shop/product'
    | '/shop/search'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/category'
    | '/shop/checkout'
    | '/shop/nightmare'
    | '/shop/orders'
    | '/shop/popup'
    | '/shop/product'
    | '/shop/search'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopNightmareRoute: typeof ShopNightmareRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopPopupRoute: typeof ShopPopupRoute
  ShopProductRoute: typeof ShopProductRoute
  ShopSearchRoute: typeof ShopSearchRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/search': {
      id: '/shop/search'
      path: '/shop/search'
      fullPath: '/shop/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/product': {
      id: '/shop/product'
      path: '/shop/product'
      fullPath: '/shop/product'
      preLoaderRoute: typeof ShopProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/popup': {
      id: '/shop/popup'
      path: '/shop/popup'
      fullPath: '/shop/popup'
      preLoaderRoute: typeof ShopPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/orders': {
      id: '/shop/orders'
      path: '/shop/orders'
      fullPath: '/shop/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/nightmare': {
      id: '/shop/nightmare'
      path: '/shop/nightmare'
      fullPath: '/shop/nightmare'
      preLoaderRoute: typeof ShopNightmareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/category': {
      id: '/shop/category'
      path: '/shop/category'
      fullPath: '/shop/category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/shop/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/account': {
      id: '/shop/account'
      path: '/shop/account'
      fullPath: '/shop/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopAccountRoute: ShopAccountRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopNightmareRoute: ShopNightmareRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopPopupRoute: ShopPopupRoute,
  ShopProductRoute: ShopProductRoute,
  ShopSearchRoute: ShopSearchRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
